import footer from "../components/footer/footer";

export const metadata = {
  title: 'Bolsonaro Preso Amanhã',
  description: 'Generated by Next.js',
  icons: {
    icon: ['/favicon.ico'],
    apple: ['/apple-touch-icon.png'],
    shortcut: ['/apple-touch-icon.png'],
  },
  manifest: '/site.webmanifest'
}


export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        {children}
        {footer}
      </body>
    </html>
  )
}
